### ISSUE TITLE
Building locally

### ISSUE THREAD

**Issue by zdrummond** [jnormington/trello-to-clubhouse.io#12]
When I grab the repo and try to build, I get this error;

`./clubhouse_options.go:17: undefined: clubhouse.Member`

When I look at the Go Clubhouse library I think you [use](https://github.com/jnormington/clubhouse-go), I don't see Member defined.

Not sure what is going on. Thanks for any help!

Note: I am relatively new to Go

**Comment by jnormington** [comment]
Hey @zdrummond,

You are quite right - I just looked and realized - that I never merged the branch I created to support the V2 upgrade for Clubhouse on that repo. But I had that branch checked out locally so my binary was built from that branch I had checked out.

If you update the clubhouse-go that you've already pulled - you should now be able to build the binary locally.

Sorry for the confusion and thanks for the heads up about that issue.
